# =============================================================================
# NEXTCLOUD PERSISTENT VOLUME CLAIMS
# =============================================================================
# PVCs für Nextcloud NAS mit Web-GUI

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: shared-services
  labels:
    app: nextcloud
    component: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
  namespace: shared-services
  labels:
    app: nextcloud
    component: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-apps-pvc
  namespace: shared-services
  labels:
    app: nextcloud
    component: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
